on:
  push:
    branches:
      - main

jobs:
  deploy-live:
    runs-on: ubuntu-latest
    steps:
      - name: get latest code
        uses: actions/checkout@v2
      - name: install node
        uses: actions/setup-node@v2
      - name: install dependencies
        run: npm install
      - name: build app
        run: npm run build
      - name: upload files
        id: upload
        uses: Creepios/sftp-action@v1.0.3
        with:
          host: access800891440.webspace-data.io
          port: 22
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          localPath: ./build/
          remotePath: ./